// taro/src/pages/shortpassword/index.vue
<template>
  <div class="demo">
    <nut-shortpassword
      v-model="state.value"
      v-model:visible="state.visible"
      :no-button="state.noButton"
      :length="state.length"
      :error-msg="state.errorMsg"
      @change="methods.onChange"
      @complete="methods.onComplete"
      @ok="methods.onOk"
      @tips="methods.onTips"
      @close="methods.close"
      @cancel="methods.cancel"
    >
    </nut-shortpassword>
    <nut-cell
      title="基础用法"
      is-link
      @click="
        state.visible = true;
        state.noButton = true;
        state.length = 6;
        state.errorMsg = '';"
    ></nut-cell>
    <nut-cell
      title="显示按钮组"
      is-link
      @click="
        state.visible = true;
        state.noButton = false;
        state.length = 6;
        state.errorMsg = '';"
    ></nut-cell>
    <nut-cell
      title="自定义密码长度4"
      is-link
      @click="
        state.visible = true;
        state.noButton = true;
        state.length = 4;
        state.errorMsg = '';"
    ></nut-cell>
    <nut-cell
      title="忘记密码提示语事件回调"
      is-link
      @click="
        state.visible = true;
        state.length = 6;
        state.errorMsg = '';
        state.noButton = true;"
    ></nut-cell>
    <nut-cell
      title="错误提示语"
      is-link
      @click="
        state.visible = true;
        state.length = 6;
        state.noButton = true;
        state.errorMsg = '请输入正确密码';"
    ></nut-cell>
  </div>
</template>

<script lang="ts">
import { reactive, getCurrentInstance, defineComponent } from 'vue';
export default defineComponent({
  setup() {
    let { proxy } = getCurrentInstance() as any;

    const state = reactive({
      visible: false,
      noButton: true,
      value: '',
      errorMsg: '',
      length: 6
    });
    const methods = {
      onChange(val: string) {
        val && proxy.$toast.text(val);
      },
      onOk(val: string) {
        val && proxy.$toast.text(val);
        state.visible = false;
      },
      onComplete() {},
      onTips() {
        proxy.$toast.text('执行忘记密码逻辑');
      },
      close() {
        proxy.$toast.text('点击icon关闭弹窗');
      },
      cancel() {
        proxy.$toast.text('点击取消按钮关闭弹窗');
      }
    };

    return {
      state,
      methods
    };
  }
});
</script>

<style lang="scss" scoped></style>

// react-taro/src/components/shortpassword/shortpassword.tsx
import React, { useState } from 'react'
import { ShortPassword, Cell, Toast } from '@nutui/nutui-react-taro'

const ShortPasswordDemo = () => {
  const [visible1, setVisible1] = useState(false)
  const [visible2, setVisible2] = useState(false)
  const [visible3, setVisible3] = useState(false)
  const [visible4, setVisible4] = useState(false)
  const [value, setValue] = useState<string | number>('')
  const change = (value: number | string) => {
    setValue(value)
  }
  const onTips = () => {
    Toast.text('执行忘记密码提示语')
  }
  return (
    <div className="demo">
      <h2>基础用法</h2>
      <Cell
        title="基础用法"
        isLink
        onClick={() => {
          setVisible1(true)
        }}
      />
      <ShortPassword
        visible={visible1}
        modelValue={value}
        onClose={() => {
          setVisible1(false)
          setValue('')
        }}
        onChange={(value) => change(value)}
      />
      <h2>显示按钮组</h2>
      <Cell
        title="显示按钮组"
        isLink
        onClick={() => {
          setVisible2(true)
        }}
      />
      <ShortPassword
        visible={visible2}
        modelValue={value}
        onClose={() => {
          setVisible2(false)
          setValue('')
        }}
        noButton={false}
        onOk={() => {
          setVisible2(false)
        }}
        onCancel={() => {
          setVisible2(false)
        }}
      />
      <h2>自定义密码长度4</h2>
      <Cell
        title="自定义密码长度4"
        isLink
        onClick={() => {
          setVisible3(true)
        }}
      />
      <ShortPassword
        visible={visible3}
        modelValue={value}
        onClose={() => {
          setVisible3(false)
          setValue('')
        }}
        length={4}
      />
      <h2>忘记密码提示语事件回调</h2>
      <Cell
        title="忘记密码提示语事件回调"
        isLink
        onClick={() => {
          setVisible4(true)
        }}
      />
      <ShortPassword
        visible={visible4}
        modelValue={value}
        onClose={() => {
          setVisible4(false)
          setValue('')
        }}
        onTips={() => onTips()}
      />
    </div>
  )
}

export default ShortPasswordDemo
