// v4-test/ailululu/vite/src/views/Swiper.vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: sueRimn
 * @Date: 2023-01-07 11:08:51
 * @LastEditors: sueRimn
 * @LastEditTime: 2023-01-07 13:52:35
-->
<template>
  <div class="demo">
    <!-- <nut-swiper
      :init-page="page"
      :pagination-visible="true"
      pagination-color="#426543"
      auto-play="3000"
    >
      <nut-swiper-item v-for="item in list" :key="item">
        <img :src="item" alt="" />
      </nut-swiper-item>
    </nut-swiper> -->
    <br />
    <nut-swiper :init-page="page3" :loop="true" @change="change">
      <nut-swiper-item>
        <img
          src="https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg"
          alt=""
        />
      </nut-swiper-item>
      <nut-swiper-item>
        <img
          src="https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg"
          alt=""
        />
      </nut-swiper-item>
      <nut-swiper-item>
        <img
          src="https://storage.360buyimg.com/jdc-article/welcomenutui.jpg"
          alt=""
        />
      </nut-swiper-item>
      <nut-swiper-item>
        <img
          src="https://storage.360buyimg.com/jdc-article/fristfabu.jpg"
          alt=""
        />
      </nut-swiper-item>
      <template v-slot:page>
        <div class="page">{{ current }}/4</div>
      </template>
    </nut-swiper>
    <nut-swiper
      :init-page="page"
      :loop="true"
      ref="swiper"
      direction="vertical"
      height="150"
      style="height: 150px"
      :is-center="true"
    >
      <nut-swiper-item v-for="item in list1" :key="item">
        <img :src="item" alt="" />
      </nut-swiper-item>
    </nut-swiper>
    <view class="nut-swiper-btns">
      <span class="nut-swiper-btns__left" @click="handlePrev"> left </span>
      <span class="nut-swiper-btns__left" @click="handleNext"> right </span>
    </view>
  </div>
</template>

<script lang="ts">
import { toRefs, reactive, ref, onMounted } from "vue";

interface Item {
  name: string;
  subname?: string;
  color?: string;
  disable?: boolean;
  loading?: boolean;
}
export default {
  props: {},
  setup() {
    const swiper = ref(null);
    const state = reactive({
      page: 2,
      page3: 0,
      current: 1,
      list: [] as string[],
      list1: [
        "https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg",
        "https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg",
        "https://storage.360buyimg.com/jdc-article/welcomenutui.jpg",
        "https://storage.360buyimg.com/jdc-article/fristfabu.jpg",
      ],
    });
    // const handleClickStep = (index: number) => {
    //   console.log(index);
    // };
    onMounted(() => {
      setTimeout(() => {
        state.list = [
          "https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg",
          "https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg",
          "https://storage.360buyimg.com/jdc-article/welcomenutui.jpg",
          "https://storage.360buyimg.com/jdc-article/fristfabu.jpg",
        ];
      }, 3000);
    });

    const change = (index: number) => {
      state.current = index + 1;
    };

    const handlePrev = () => {
      swiper.value.prev();
    };
    const handleNext = () => {
      swiper.value.next();
    };

    return {
      ...toRefs(state),
      change,
      swiper,
      handlePrev,
      handleNext,
    };
  },
};
</script>

<style lang="scss" scoped>
.nut-swiper-item {
  line-height: 150px;
  img {
    width: 100%;
    height: 100%;
  }
}
.page {
  position: absolute;
  bottom: 0;
  right: 0;
  width: 46px;
  height: 22px;
  background: rgba(0, 0, 0, 0.33);
  border-radius: 22px;
  text-align: center;
  color: #fff;
  font-size: 14px;
}
.nut-swiper-item {
  line-height: 150px;
  img {
    width: 100%;
    height: 100%;
  }
  ::v-deep(.nut-swiper-pagination-vertical) {
    i {
      width: 6px;
      height: 6px;
      border-radius: 50%;
      &.active {
        height: 18px;
        border-radius: 5px;
      }
    }
  }
}
</style>

// react-taro/src/components/swiper/swiper.tsx
import React, { useState, useEffect } from 'react'
import './demo.scss'
import { useTranslate } from '@/sites/assets/locale/taro'
import { SwiperItem, Swiper, Icon } from '@nutui/nutui-react-taro'

interface T {
  basic: string
  asyc: string
  dynamicDel: string
  size: string
  indicator: string
  btns: string
  vertical: string
  horizontalCenter: string
  verticalCenter: string
}
const SwiperDemo = () => {
  const [translated] = useTranslate<T>({
    'zh-CN': {
      basic: '基本用法',
      asyc: '异步加载(3s)',
      dynamicDel: '动态加载',
      size: '自定义大小',
      indicator: '自定义指示器',
      btns: '手动切换',
      vertical: '垂直方向',
      horizontalCenter: '水平居中展示',
      verticalCenter: '垂直居中展示',
    },
    'en-US': {
      basic: 'Basic Usage',
      asyc: 'Asynchronous loading(3s)',
      dynamicDel: 'Dynamic loading',
      size: 'Custom size',
      indicator: 'Custom indicator',
      btns: 'Manual switching',
      vertical: 'Vertical direction',
      horizontalCenter: 'Horizontal center display',
      verticalCenter: 'Vertical center display',
    },
  })
  const swiperRef = React.useRef<any>(null)
  const [height, setHeight] = useState<any>(150)
  const [paginationColor, setPaginationColor] = useState<string>('#426543')
  const [initPage1, setInitPage1] = useState<any>(0)
  const [initPage2, setInitPage2] = useState<any>(0)
  const [initPage3, setInitPage3] = useState<any>(0)
  const [initPage4, setInitPage4] = useState<any>(0)
  const [initPage5, setInitPage5] = useState<any>(0)
  const [initPage6, setInitPage6] = useState<any>(0)
  const [initPage7, setInitPage7] = useState<any>(0)
  const [initPage8, setInitPage8] = useState<any>(0)
  const [initPage9, setInitPage9] = useState<any>(0)
  const [current, setCurrent] = useState(1)
  const [current2, setCurrent2] = useState(1)
  const [list1, setList1] = useState<string[]>([])
  const [list2, setList2] = useState<string[]>([
    'https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg',
    'https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg',
    'https://storage.360buyimg.com/jdc-article/welcomenutui.jpg',
    'https://storage.360buyimg.com/jdc-article/fristfabu.jpg',
  ])

  const list = [
    'https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg',
    'https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg',
    'https://storage.360buyimg.com/jdc-article/welcomenutui.jpg',
    'https://storage.360buyimg.com/jdc-article/fristfabu.jpg',
  ]
  const onChange = (e: number) => {}
  const handlePrev = () => {
    swiperRef.current.prev()
  }
  const handleNext = () => {
    swiperRef.current.next()
  }

  useEffect(() => {
    setTimeout(() => {
      const arr: any = list.slice()
      setList1(arr)
      const arr2 = list2.slice()
      arr2.splice(1, 1)
      setList2(arr2)
    }, 3000)
  }, [])
  return (
    <div className="demo padding">
      <h2>{translated.basic}</h2>
      <div className="demo-box" style={{ height: 150 }}>
        <Swiper
          height={height}
          paginationColor={paginationColor}
          autoPlay="2000"
          initPage={initPage1}
          onChange={onChange}
          paginationVisible
        >
          {list.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
      </div>
      <h2>{translated.asyc}</h2>
      <div className="demo-box" style={{ height: 150 }}>
        <Swiper
          height={height}
          paginationColor={paginationColor}
          autoPlay="2000"
          initPage={initPage2}
          onChange={onChange}
          paginationVisible
        >
          {list1.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
      </div>
      <h2>{translated.dynamicDel}</h2>
      <div className="demo-box" style={{ height: 150 }}>
        <Swiper
          height={height}
          paginationColor={paginationColor}
          autoPlay="2000"
          initPage={initPage3}
          onChange={onChange}
          paginationVisible
        >
          {list2.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
      </div>

      <h2>{translated.size}</h2>
      <div className="demo-box" style={{ height: 150 }}>
        <Swiper initPage={initPage4} width="300" loop={false}>
          {list.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
      </div>
      <h2>{translated.indicator}</h2>
      <div className="demo-box" style={{ height: 150 }}>
        <Swiper
          loop
          initPage={initPage5}
          onChange={(e) => setCurrent(e + 1)}
          pageContent={<div className="page"> {current}/4 </div>}
        >
          {list.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
      </div>
      <h2>{translated.btns}</h2>
      <div className="demo-box" style={{ height: 150 }}>
        <Swiper
          ref={swiperRef}
          loop
          initPage={initPage6}
          onChange={(e) => setCurrent2(e + 1)}
          pageContent={<div className="page"> {current2}/4 </div>}
        >
          {list.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
        <div className="nut-swiper-btns">
          <span className="nut-swiper-btns__left" onClick={(e) => handlePrev()}>
            <Icon name="left" />
          </span>
          <span className="nut-swiper-btns__left" onClick={(e) => handleNext()}>
            <Icon name="right" />
          </span>
        </div>
      </div>
      <h2>{translated.vertical}</h2>
      <div className="demo-box vertical-center" style={{ height: 150 }}>
        <Swiper
          loop
          initPage={initPage7}
          direction="vertical"
          autoPlay="3000"
          height="150"
          paginationVisible
        >
          {list.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
      </div>
      <h2>{translated.horizontalCenter}</h2>
      <div className="demo-box " style={{ height: 150 }}>
        <Swiper
          loop={false}
          initPage={initPage8}
          autoPlay="0"
          height="150"
          paginationVisible
          width="280"
          isCenter
        >
          {list.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
      </div>
      <h2>{translated.verticalCenter}</h2>
      <div className="demo-box vertical-center">
        <Swiper
          loop={false}
          initPage={initPage9}
          direction="vertical"
          autoPlay="0"
          height="220"
          paginationVisible
          isCenter
          style={{ height: '280px' }}
        >
          {list.map((item) => {
            return (
              <SwiperItem key={item}>
                <img src={item} alt="" />
              </SwiperItem>
            )
          })}
        </Swiper>
      </div>
    </div>
  )
}

export default SwiperDemo
