// react-taro/src/components/switch/switch.tsx
import React, { useState } from 'react'
import { Switch, Cell } from '@nutui/nutui-react-taro'
import Header from '@/sites/components/header'
import Taro from '@tarojs/taro'

const SwitchDemo = () => {
  const [checkedAsync, setCheckedAsync] = useState(true)
  const onChange = (
    value: boolean,
    event: React.MouseEvent<Element, MouseEvent>
  ) => {
    console.log(`触发了onChange事件，开关状态：${value}`)
  }
  const onChangeAsync = (value: boolean, event: any) => {
    console.log(`2秒后异步触发 ${value}`)
    setTimeout(() => {
      setCheckedAsync(value)
    }, 2000)
  }
  return (
    <>
      <Header />
      <div className={`demo ${Taro.getEnv() === 'WEB' ? 'web' : ''}`}>
        <h2>基础用法</h2>
        <Cell>
          <Switch checked />
        </Cell>
        <h2>禁用状态</h2>
        <Cell>
          <Switch checked disable />
        </Cell>
        <h2>onChange事件</h2>
        <Cell>
          <Switch onChange={(value, event) => onChange(value, event)} />
        </Cell>
        <h2>异步控制</h2>
        <Cell>
          <Switch
            checked={checkedAsync}
            isAsync
            onChange={(value, event) => onChangeAsync(value, event)}
          />
        </Cell>
        <h2>自定义颜色</h2>
        <Cell>
          <Switch activeColor="blue" />
        </Cell>
        <h2>支持文字</h2>
        <Cell>
          <Switch activeText="开" inactiveText="关" />
        </Cell>
      </div>
    </>
  )
}

export default SwitchDemo

// taro/src/pages/switch/index.vue
<template>
  <div class="demo">
    <h2>基础用法</h2>
    <nut-cell>
      <nut-switch v-model="checked" />
    </nut-cell>

    <h2>禁用状态</h2>
    <nut-cell>
      <nut-switch v-model="checked" disable />
    </nut-cell>

    <h2>change事件</h2>
    <nut-cell>
      <nut-switch v-model="checked" @change="change" />
    </nut-cell>

    <h2>异步控制</h2>
    <nut-cell>
      <nut-switch :model-value="checkedAsync" @change="changeAsync" />
    </nut-cell>

    <h2>自定义颜色</h2>
    <nut-cell>
      <nut-switch
        v-model="checked"
        @change="switchChange"
        active-color="blue"
      />
    </nut-cell>

    <h2>支持文字</h2>
    <nut-cell>
      <nut-switch
        v-model="checked"
        @change="switchChange"
        active-text="开"
        inactive-text="关"
      />
    </nut-cell>
  </div>
</template>

<script lang="ts">
import { ref, getCurrentInstance, defineComponent } from 'vue';
export default defineComponent({
  setup() {
    let { proxy } = getCurrentInstance() as any;
    const checked = ref(true);
    const checkedAsync = ref(true);

    const change = (value: boolean) => {
      proxy.$toast.text(`触发了change事件，开关状态：${value}`);
    };
    const changeAsync = (value: boolean) => {
      proxy.$toast.text(`2秒后异步触发 ${value}`);
      setTimeout(() => {
        checkedAsync.value = value;
      }, 2000);
    };

    return {
      checked,
      checkedAsync,
      change,
      changeAsync
    };
  }
});
</script>

<style lang="scss" scoped></style>
