// nutui-react/react-taro/src/components/range/range.tsx
import React, { useState } from 'react'
import { useTranslate } from '@/sites/assets/locale/taro'
import { Range, Cell, Toast } from '@nutui/nutui-react-taro'
import './demo.scss'

interface T {
  title: string
  title1: string
  title2: string
  title3: string
  title4: string
  title5: string
  title6: string
  title7: string
  title8: string
  title9: string
  title10: string
}

const RangeDemo = () => {
  const [translated] = useTranslate<T>({
    'zh-CN': {
      title: '基础用法',
      title1: '双滑块',
      title2: '指定范围',
      title3: '设置步长',
      title4: '隐藏范围',
      title5: '隐藏标签',
      title6: '禁用',
      title7: '自定义样式',
      title8: '自定义按钮',
      title9: '垂直方向',
      title10: '刻度标记',
    },
    'en-US': {
      title: 'Basic Usage',
      title1: 'Dual thumb',
      title2: 'Range',
      title3: 'Step Size',
      title4: 'Hidden Range',
      title5: 'Hidden Tag',
      title6: 'Disabled',
      title7: 'Custom Style',
      title8: 'Custom Button',
      title9: 'Vertical',
      title10: 'Marks',
    },
  })
  const cellStyle = {
    padding: '40px 18px',
  }
  const verticalStyle = {
    height: '180px',
    padding: '10px',
  }
  const [value0, SetValue0] = useState([30, 60])
  const [value1, SetValue1] = useState(30)
  const [value2, SetValue2] = useState(60)
  const [value3, SetValue3] = useState(20)
  const [value4, SetValue4] = useState([20, 80])
  const [value5, SetValue5] = useState(60)
  const [value6, SetValue6] = useState([20, 80])
  const [value7, SetValue7] = useState(60)
  const [value8, SetValue8] = useState([20, 80])
  const [marks, SetMarks] = useState({
    0: 0,
    20: 20,
    40: 40,
    60: 60,
    80: 80,
    100: 100,
  })
  const change = (value: any, name?: string) => {
    Toast.text(`当前值：${value}`)
    switch (name) {
      case 'value0':
        SetValue0(value)
        break
      case 'value1':
        SetValue1(value)
        break
      case 'value2':
        SetValue2(value)
        break
      case 'value3':
        SetValue3(value)
        break
      case 'value4':
        SetValue4(value)
        break
      case 'value5':
        SetValue5(value)
        break
      case 'value6':
        SetValue6(value)
        break
      case 'value7':
        SetValue7(value)
        break
      case 'value8':
        SetValue8(value)
        break
      default:
        break
    }
  }

  return (
    <>
      <div className="demo">
        <h2>{translated.title}</h2>
        <Cell style={cellStyle}>
          <Range modelValue={40} />
        </Cell>
        <h2>{translated.title1}</h2>
        <Cell style={cellStyle}>
          <Range
            range
            modelValue={value0}
            change={(value: any) => {
              change(value, 'value0')
            }}
          />
        </Cell>
        <h2>{translated.title2}</h2>
        <Cell style={cellStyle}>
          <Range
            modelValue={100}
            max={10}
            min={-10}
            change={(value: any) => {
              change(value)
            }}
          />
        </Cell>
        <h2>{translated.title3}</h2>
        <Cell style={cellStyle}>
          <Range
            modelValue={value1}
            step={5}
            change={(value: any) => {
              change(value, 'value1')
            }}
          />
        </Cell>
        <h2>{translated.title4}</h2>
        <Cell style={cellStyle}>
          <Range
            modelValue={30}
            hiddenRange
            change={(value: any) => {
              change(value)
            }}
          />
        </Cell>
        <h2>{translated.title5}</h2>
        <Cell style={cellStyle}>
          <Range
            modelValue={20}
            hiddenTag
            change={(value: any) => {
              change(value)
            }}
          />
        </Cell>
        <h2>{translated.title6}</h2>
        <Cell style={cellStyle}>
          <Range
            modelValue={50}
            disabled
            change={(value: any) => {
              change(value)
            }}
          />
        </Cell>
        <h2>{translated.title7}</h2>
        <Cell style={cellStyle}>
          <Range
            className="test-range"
            modelValue={40}
            inactiveColor="rgba(163,184,255,1)"
            buttonColor="rgba(52,96,250,1)"
            activeColor="linear-gradient(315deg, rgba(73,143,242,1) 0%,rgba(73,101,242,1) 100%)"
            style={{ color: 'red' }}
            change={(value: number) => {
              change(value)
            }}
          />
        </Cell>
        <h2>{translated.title8}</h2>
        <Cell style={cellStyle}>
          <Range
            modelValue={value2}
            button={<div className="range-custom-button">{value2}</div>}
            change={(value: number) => {
              change(value, 'value2')
            }}
          />
        </Cell>
        <h2>{translated.title9}</h2>
        <Cell style={verticalStyle}>
          <div style={{ width: '150px' }}>
            <Range
              modelValue={value3}
              vertical
              change={(value: number) => {
                change(value, 'value3')
              }}
            />
          </div>
          <div style={{ width: '150px' }}>
            <Range
              modelValue={value4}
              vertical
              range
              change={(value: number) => {
                change(value, 'value4')
              }}
            />
          </div>
        </Cell>
        <h2>{translated.title10}</h2>
        <Cell style={cellStyle}>
          <Range
            modelValue={value5}
            hiddenRange
            marks={marks}
            change={(value: number) => {
              change(value, 'value5')
            }}
          />
        </Cell>
        <Cell style={cellStyle}>
          <Range
            modelValue={value6}
            marks={marks}
            range
            change={(value: number) => {
              change(value, 'value6')
            }}
          />
        </Cell>

        <Cell style={verticalStyle}>
          <Range
            modelValue={value7}
            vertical
            hiddenRange
            marks={marks}
            change={(value: number) => {
              change(value, 'value7')
            }}
          />
          <Range
            modelValue={value8}
            vertical
            marks={marks}
            range
            change={(value: number) => {
              change(value, 'value8')
            }}
          />
        </Cell>
      </div>
    </>
  )
}

export default RangeDemo

// taro/src/pages/range/index.vue
<template>
  <div class="demo">
    <h2>基础用法</h2>
    <nut-cell class="cell">
      <nut-range v-model="value1" @change="onChange"></nut-range>
    </nut-cell>
    <h2>双滑块</h2>
    <nut-cell class="cell">
      <nut-range range v-model="value2" @change="onChange"></nut-range>
    </nut-cell>
    <h2>指定范围</h2>
    <nut-cell class="cell">
      <nut-range
        v-model="value3"
        :max="10"
        :min="-10"
        @change="onChange"
      ></nut-range>
    </nut-cell>
    <h2>设置步长</h2>
    <nut-cell class="cell">
      <nut-range v-model="value4" :step="5" @change="onChange"></nut-range>
    </nut-cell>
    <h2>隐藏范围</h2>
    <nut-cell class="cell">
      <nut-range hidden-range v-model="value5" @change="onChange"></nut-range>
    </nut-cell>
    <h2>隐藏标签</h2>
    <nut-cell class="cell">
      <nut-range hidden-tag v-model="value6" @change="onChange"></nut-range>
    </nut-cell>
    <h2>禁用</h2>
    <nut-cell class="cell">
      <nut-range disabled v-model="value7"></nut-range>
    </nut-cell>
    <h2>自定义样式</h2>
    <nut-cell class="cell">
      <nut-range
        v-model="value8"
        @change="onChange"
        inactive-color="rgba(163,184,255,1)"
        button-color="rgba(52,96,250,1)"
        active-color="linear-gradient(315deg, rgba(73,143,242,1) 0%,rgba(73,101,242,1) 100%)"
      ></nut-range>
    </nut-cell>
    <h2>自定义按钮</h2>
    <nut-cell class="cell">
      <nut-range v-model="value9" @change="onChange">
        <template #button>
          <div class="custom-button">{{ value10 }}</div>
        </template>
      </nut-range>
    </nut-cell>
  </div>
</template>

<script lang="ts">
import { toRefs, reactive, defineComponent } from 'vue';
import { Toast } from '@nutui/nutui';

export default defineComponent({
  props: {},
  setup() {
    const state = reactive({
      value1: 40,
      value2: [20, 80],
      value3: 0,
      value4: 20,
      value5: 30,
      value6: 40,
      value7: 50,
      value8: 40,
      value9: 60,
      value10: 50
    });
    const onChange = (value: number) => Toast.text('当前值：' + value);
    return {
      ...toRefs(state),
      onChange
    };
  }
});
</script>

<style lang="scss" scoped>
.cell {
  padding: 40px 18px;
}
.custom-button {
  width: 26px;
  color: #fff;
  font-size: 10px;
  line-height: 18px;
  text-align: center;
  background-color: #ee0a24;
  border-radius: 100px;
}
</style>
