// v4-test/eiinu/vite/src/views/Notify.vue
<template>
  <div class="demo">
    <nut-cell-group :title="translate('basic')">
      <nut-cell is-Link @click="baseNotify(translate('basic'))">{{ translate('basic') }}</nut-cell>
    </nut-cell-group>
    <nut-cell-group :title="translate('t1')">
      <nut-cell is-Link @click="primaryNotify(translate('primaryNotify'))">{{ translate('primaryNotify') }}</nut-cell>
      <nut-cell is-Link @click="successNotify(translate('successNotify'))">{{ translate('successNotify') }}</nut-cell>
      <nut-cell is-Link @click="errorNotify(translate('errorNotify'))">{{ translate('errorNotify') }}</nut-cell>
      <nut-cell is-Link @click="warningNotify(translate('warningNotify'))">{{ translate('warningNotify') }}</nut-cell>
    </nut-cell-group>
    <nut-cell-group :title="translate('t2')">
      <nut-cell is-Link @click="cusBgNotify(translate('cusBgNotify'))"> {{ translate('cusBgNotify') }} </nut-cell>
      <nut-cell is-Link @click="timeNotify(translate('t3'))"> {{ translate('t3') }} </nut-cell>
      <nut-cell is-Link @click="positionNotify(translate('cusPostion'))"> {{ translate('cusPostion') }} </nut-cell>
    </nut-cell-group>
    <nut-cell-group :title="translate('useTemplate')">
      <nut-cell is-Link @click="showNotify">{{ translate('useTemplate') }}</nut-cell>
      <nut-notify v-model:visible="show" :duration="2000">
        <span>Content</span>
      </nut-notify>
    </nut-cell-group>
  </div>
</template>

<script lang="ts">
import { createComponent } from '@/packages/utils/create';
import { showNotify } from '@nutui/nutui';
import { ref } from 'vue';
const { createDemo, translate } = createComponent('notify');
import { useTranslate } from '@/sites/assets/util/useTranslate';
const initTranslate = () =>
  useTranslate({
    'zh-CN': {
      basic: '基本用法',
      t1: '通知类型',
      t2: '自定义',
      t3: '自定义时长',
      cusPostion: '自定义位置',
      useTemplate: '组件调用',
      primaryNotify: '主要通知',
      successNotify: '成功通知',
      errorNotify: '危险通知',
      warningNotify: '警告通知',
      cusBgNotify: '自定义背景色和字体颜色'
    },
    'en-US': {
      basic: 'Basic Usage',
      t1: 'Notify Type',
      t2: 'Custom',
      t3: 'Custom Duration',
      cusPostion: 'Custom Postion',
      useTemplate: 'Template use',
      primaryNotify: 'Primary Notify',
      successNotify: 'Success Notify',
      errorNotify: 'Error Notify',
      warningNotify: 'Warning Notify',
      cusBgNotify: 'Customize background and font colors'
    }
  });
export default createDemo({
  setup() {
    initTranslate();
    const baseNotify = (msg: string) => {
      console.log(showNotify)
      // showNotify.text(msg, {
      //   onClose: () => {
      //     console.log('close');
      //   },
      //   onClick: () => {
      //     console.log('click');
      //   }
      // });
    };
    const primaryNotify = (msg: string) => {
      Notify.primary(msg, { duration: 1000 });
    };
    const successNotify = (msg: string) => {
      Notify.success(msg);
    };
    const errorNotify = (msg: string) => {
      Notify.danger(msg);
    };
    const warningNotify = (msg: string) => {
      Notify.warn(msg);
    };
    const cusBgNotify = (msg: string) => {
      Notify.text(msg, { color: '#ad0000', background: '#ffe1e1' });
    };
    const timeNotify = (msg: string) => {
      Notify.text(msg, { duration: 1000 });
    };
    const positionNotify = (msg: string) => {
      Notify.text(msg, { position: 'bottom' });
    };
    const show = ref(false);
    const showNotify = () => {
      show.value = true;
    };
    return {
      baseNotify,
      primaryNotify,
      successNotify,
      errorNotify,
      warningNotify,
      cusBgNotify,
      timeNotify,
      positionNotify,
      show,
      showNotify,
      translate
    };
  }
});
</script>

<style lang="scss" scoped></style>

// react-taro-2.0/src/components/notify/notify.tsx
import React, { useState } from 'react'
import Taro from '@tarojs/taro'
import { useTranslate } from '@/sites/assets/locale/taro'
import { Notify, Cell, CellGroup } from '@nutui/nutui-react-taro'
import Header from '@/sites/components/header'

interface T {
  basic: string
  numbers: string
  autoHeight: string
  readOnly: string
  readOnlyState: string
  disabled: string
  disabledState: string
}
const NotifyDemo = () => {
  const [translated] = useTranslate({
    'zh-CN': {
      basic: '基本用法',
      t1: '通知类型',
      t2: '自定义样式',
      t3: '自定义时长为5秒',
      cusPostion: '自定义位置',
      useTemplate: '组件调用',
      primaryNotify: '主要通知',
      successNotify: '成功通知',
      errorNotify: '危险通知',
      warningNotify: '警告通知',
      cusBgNotify: '自定义背景色和字体颜色',
    },
    'en-US': {
      basic: 'Basic Usage',
      t1: 'Notify Type',
      t2: 'Custom Style',
      t3: 'Custom Duration 5s',
      cusPostion: 'Custom Postion',
      useTemplate: 'Template use',
      primaryNotify: 'Primary Notify',
      successNotify: 'Success Notify',
      errorNotify: 'Error Notify',
      warningNotify: 'Warning Notify',
      cusBgNotify: 'Customize background and font colors',
    },
  })
  const [showNotify, SetShowNotify] = useState(false)
  const [customShow, SetCustomShow] = useState(false)
  const [states, SetStates] = useState({
    message: '',
    type: 'danger',
    duration: 2000,
    position: 'top',
  })
  const changeNotify = (
      message: string,
      type?: string,
      duration?: number,
      position?: string
  ) => {
    const change = Object.assign(states, {
      message,
      type,
      duration,
      position,
    })
    SetStates(change)
  }

  return (
      <>
        <Header />
        <div
            className={`demo ${Taro.getEnv() === 'WEB' ? 'web' : ''}`}
            style={{ paddingBottom: '30px' }}
        >
          <Notify
              visible={showNotify}
              type={states.type}
              duration={states.duration}
              position={states.position}
              onClose={() => {
                SetShowNotify(false)
              }}
              onClick={() => {
                console.log('click')
              }}
          >
            {states.message}
          </Notify>
          <h2>{translated.basic}</h2>
          <Cell
              title={translated.basic}
              onClick={(event: React.MouseEvent) => {
                changeNotify(translated.basic)
                SetShowNotify(true)
              }}
          />
          <h2>{translated.t1}</h2>
          <CellGroup>
            <Cell
                title={translated.primaryNotify}
                onClick={(event: React.MouseEvent) => {
                  changeNotify(translated.primaryNotify, 'primary')
                  SetShowNotify(true)
                }}
            />
            <Cell
                title={translated.successNotify}
                onClick={(event: React.MouseEvent) => {
                  changeNotify(translated.successNotify, 'success')
                  SetShowNotify(true)
                }}
            />
            <Cell
                title={translated.errorNotify}
                onClick={(event: React.MouseEvent) => {
                  changeNotify(translated.errorNotify, 'danger')
                  SetShowNotify(true)
                }}
            />
            <Cell
                title={translated.warningNotify}
                onClick={(event: React.MouseEvent) => {
                  changeNotify(translated.warningNotify, 'warning')
                  SetShowNotify(true)
                }}
            />
          </CellGroup>
          <h2>{translated.t2}</h2>
          <Notify
              className="customer"
              visible={customShow}
              style={{
                '--nutui-notify-text-color': '#ad0000',
                '--nutui-notify-base-background-color': '#ffe1e1',
              }}
              onClose={() => {
                SetCustomShow(false)
              }}
          >
            {translated.cusBgNotify}
          </Notify>
          <Cell
              title={translated.cusBgNotify}
              onClick={(event: React.MouseEvent) => {
                SetCustomShow(true)
              }}
          />
          <h2>{translated.t3}</h2>
          <Cell
              title={translated.t3}
              onClick={(event: React.MouseEvent) => {
                changeNotify(translated.t3, 'base', 5000)
                SetShowNotify(true)
              }}
          />
          <Cell
              title={translated.cusPostion}
              onClick={(event: React.MouseEvent) => {
                changeNotify(translated.cusPostion, 'base', 2000, 'bottom')
                SetShowNotify(true)
              }}
          />
        </div>
      </>
  )
}

export default NotifyDemo
