// taro/src/pages/swiper/index.vue
<template>
  <div class="demo">
    <h2>基本用法</h2>
    <view class="demo-box">
      <nut-swiper
        :init-page="page"
        :pagination-visible="true"
        pagination-color="#426543"
      >
        <nut-swiper-item v-for="item in list" :key="item">
          <img :src="item" alt="" />
        </nut-swiper-item>
      </nut-swiper>
    </view>
    <h2>自定义大小</h2>
    <view class="demo-box">
      <nut-swiper :init-page="page2" :loop="false" width="300">
        <nut-swiper-item v-for="item in list" :key="item">
          <img :src="item" alt="" />
        </nut-swiper-item>
      </nut-swiper>
    </view>
    <h2>自定义指示器</h2>
    <view class="demo-box">
      <nut-swiper :init-page="page3" :loop="true" @change="change">
        <nut-swiper-item v-for="item in list" :key="item">
          <img :src="item" alt="" />
        </nut-swiper-item>
        <template v-slot:page>
          <div class="page"> {{ current }}/4 </div>
        </template>
      </nut-swiper>
    </view>
    <h2>垂直方向</h2>
    <view class="demo-box">
      <nut-swiper
        :init-page="page4"
        :loop="true"
        auto-play="3000"
        direction="vertical"
        height="150"
        :pagination-visible="true"
        style="height: 150px"
      >
        <nut-swiper-item v-for="item in list" :key="item">
          <img :src="item" alt="" />
        </nut-swiper-item>
      </nut-swiper>
    </view>
  </div>
</template>

<script lang="ts">
import { reactive, toRefs, defineComponent } from 'vue';
export default defineComponent({
  props: {},
  setup() {
    const state = reactive({
      page: 2,
      page2: 0,
      page3: 0,
      page4: 0,
      current: 1,
      list: [
        'https://m.360buyimg.com/mobilecms/s700x280_jfs/t1/128047/5/6706/178631/5f068cefE53bff564/4dd870d8932daecf.jpg',
        'https://m.360buyimg.com/mobilecms/s700x280_jfs/t1/159602/22/7999/126515/6035f371E6f95bfee/559cb1ee48c962c9.jpg',
        'https://m.360buyimg.com/mobilecms/s700x280_jfs/t1/166846/13/7534/136440/60338b5cEd491d8b3/9e5527429136ab86.jpg',
        'https://m.360buyimg.com/mobilecms/s700x280_jfs/t1/145433/27/14059/141680/5facf066Ec402354c/530d5a316aed55fc.jpg'
      ]
    });
    const change = (index: number) => {
      state.current = index + 1;
    };
    return {
      ...toRefs(state),
      change
    };
  }
});
</script>

<style lang="scss" scoped>
.demo-box {
  .nut-swiper-item {
    line-height: 150px;
    img {
      width: 100%;
      height: 100%;
    }
  }
  .page {
    position: absolute;
    bottom: 0;
    right: 0;
    width: 46px;
    height: 22px;
    background: rgba(0, 0, 0, 0.33);
    border-radius: 22px;
    text-align: center;
    color: #fff;
    font-size: 14px;
  }
}
</style>

// react-taro-2.0/src/components/swiper/swiper.tsx
import React, {useState, useEffect, useRef} from 'react'
import './demo.scss'
import { useTranslate } from '@/sites/assets/locale/taro'
import { SwiperItem, Swiper } from '@nutui/nutui-react-taro'
import Header from '@/sites/components/header'
import Taro from '@tarojs/taro'
import {Left, Right} from "@nutui/icons-react-taro";

interface T {
  basic: string
  asyc: string
  dynamicDel: string
  size: string
  indicator: string
  btns: string
  vertical: string
  horizontalCenter: string
  verticalCenter: string
}

const SwiperDemo = () => {
  const [translated] = useTranslate<T>({
    'zh-CN': {
      basic: '基本用法',
      asyc: '异步加载(3s)',
      dynamicDel: '动态加载',
      size: '自定义大小',
      indicator: '自定义指示器',
      btns: '手动切换',
      vertical: '垂直方向',
      horizontalCenter: '水平居中展示',
      verticalCenter: '垂直居中展示',
    },
    'en-US': {
      basic: 'Basic Usage',
      asyc: 'Asynchronous loading(3s)',
      dynamicDel: 'Dynamic loading',
      size: 'Custom size',
      indicator: 'Custom indicator',
      btns: 'Manual switching',
      vertical: 'Vertical direction',
      horizontalCenter: 'Horizontal center display',
      verticalCenter: 'Vertical center display',
    },
  })

  const list = [
    'https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg',
    'https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg',
    'https://storage.360buyimg.com/jdc-article/welcomenutui.jpg',
    'https://storage.360buyimg.com/jdc-article/fristfabu.jpg',
  ]

  const [asyncList, setAsyncList] = useState<string[]>([])
  useEffect(() => {
    setTimeout(() => {
      setAsyncList(list)
    }, 3000)
  }, [])

  const [current, setCurrent] = useState(0)
  const [current2, setCurrent2] = useState(0)

  const swiperRef = useRef<any>(null)

  return (
      <>
        <Header />
        <div className={`demo ${Taro.getEnv() === 'WEB' ? 'web' : ''} padding`}>
          <h2>{translated.basic}</h2>
          <Swiper defaultValue={1} indicator>
            {list.map((item) => (
                <SwiperItem key={item}>
                  <img width="100%" height="100%" src={item} alt="" />
                </SwiperItem>
            ))}
          </Swiper>
          <h2>{translated.asyc}</h2>
          <Swiper defaultValue={0} indicator>
            {asyncList.map((item) => (
                <SwiperItem key={item}>
                  <img width="100%" height="100%" src={item} alt="" />
                </SwiperItem>
            ))}
          </Swiper>

          <h2>{translated.size}</h2>
          <Swiper
              className="swiper-demo-size"
              width={300}
              height={150}
              defaultValue={0}
              loop={false}
          >
            {list.map((item) => (
                <SwiperItem key={item}>
                  <img width="100%" height="100%" src={item} alt="" />
                </SwiperItem>
            ))}
          </Swiper>

          <h2>{translated.indicator}</h2>
          <Swiper
              defaultValue={0}
              onChange={(e) => setCurrent(e.detail.current)}
              indicator={
                <div
                    style={{
                      position: 'absolute',
                      bottom: '0',
                      right: '0',
                      width: '46px',
                      height: '22px',
                      background: 'rgba(0, 0, 0, 0.33)',
                      borderRadius: '22px',
                      textAlign: 'center',
                      color: '#fff',
                      fontSize: '14px',
                    }}
                >
                  {current + 1}/{list.length}
                </div>
              }
          >
            {list.map((item) => (
                <SwiperItem key={item}>
                  <img width="100%" height="100%" src={item} alt="" />
                </SwiperItem>
            ))}
          </Swiper>

          <h2>{translated.btns}</h2>
          <div className="demo-box" style={{ height: 150 }}>
            <Swiper
                ref={swiperRef}
                defaultValue={0}
                onChange={(e) => {
                  setCurrent2(e.detail.current)
                }}
                indicator={
                  <div className="page">
                    {current2 + 1}/{list.length}
                  </div>
                }
            >
              {list.map((item) => {
                return (
                    <SwiperItem key={item}>
                      <img src={item} alt="" />
                    </SwiperItem>
                )
              })}
            </Swiper>
            <div className="nut-swiper-btns">
            <span
                className="nut-swiper-btns__left"
                onClick={(e) => swiperRef.current?.prev()}
            >
              <Left />
            </span>
              <span
                  className="nut-swiper-btns__left"
                  onClick={(e) => swiperRef.current?.next()}
              >
              <Right />
            </span>
            </div>
          </div>
          <h2>{translated.vertical}</h2>
          <Swiper defaultValue={0} direction="vertical">
            {list.map((item) => (
                <SwiperItem key={item}>
                  <img width="100%" height="100%" src={item} alt="" />
                </SwiperItem>
            ))}
          </Swiper>
          <h2>{translated.horizontalCenter}</h2>
          <Swiper defaultValue={0} loop previousMargin="20px" nextMargin="20px">
            {list.map((item) => (
                <SwiperItem key={item}>
                  <img width="100%" height="100%" src={item} alt="" />
                </SwiperItem>
            ))}
          </Swiper>
          <h2>{translated.verticalCenter}</h2>
          <Swiper
              defaultValue={0}
              direction="vertical"
              height={220}
              previousMargin="20px"
              nextMargin="20px"
          >
            {list.map((item) => (
                <SwiperItem key={item}>
                  <img width="100%" height="100%" src={item} alt="" />
                </SwiperItem>
            ))}
          </Swiper>
        </div>
      </>
  )
}

export default SwiperDemo
