// v4-test/richard1015/vite/src/components/Popover.vue
<script lang="ts" setup>
import { h, reactive, ref } from "vue";
import { Cart2, My2 } from "@nutui/icons-vue";
const visible = ref({
  darkTheme: false,
  lightTheme: false,
  showIcon: false,
  disableAction: false,
  customColor: false,
});
const iconItemList = reactive([
  { name: "选项一" },
  { name: "选项二" },
  { name: "选项三" },
]);

const itemList = reactive([
  {
    name: "option1",
    icon: () => {
      return h(My2, {
        width: "14px",
        color: "rgba(250, 44, 25, 1)",
      });
    },
  },
  {
    name: "option2",
    icon: Cart2,
  },
  {
    name: "option3",
    icon: Location,
  },
]);

const itemListDisabled = reactive([
  {
    name: "选项一",
    disabled: true,
  },
  {
    name: "选项二",
    disabled: true,
  },
  {
    name: "选项三",
  },
]);
const handle = (str: string) => {
  console.log(str);
};
</script>
<template>
  <nut-popover
    @choose="handle('choose')"
    @open="handle('open')"
    @close="handle('close')"
    v-model:visible="visible.lightTheme"
    :duration="0.3"
    :list="iconItemList"
  >
    <template #reference>
      <nut-button type="primary" shape="square">明朗风格</nut-button>
    </template>
  </nut-popover>

  <nut-popover
    v-model:visible="visible.darkTheme"
    theme="dark"
    :list="iconItemList"
  >
    <template #reference>
      <nut-button type="primary" shape="square">暗黑风格</nut-button>
    </template>
  </nut-popover>
  <!-- 
  <nut-popover v-model:visible="visible.showIcon" theme="dark" :list="itemList">
    <template #reference>
      <nut-button type="primary" shape="square">展示图标</nut-button>
    </template>
  </nut-popover>

  <nut-popover v-model:visible="visible.disableAction" :list="itemListDisabled">
    <template #reference>
      <nut-button type="primary" shape="square">禁用选项</nut-button>
    </template>
  </nut-popover>

  <nut-popover
    v-model:visible="visible.customColor"
    :list="itemList"
    location="right-start"
    bgColor="#f00"
    theme="dark"
  >
    <template #reference>
      <nut-button type="primary" shape="square">自定义颜色</nut-button>
    </template>
  </nut-popover> -->
</template>
<style lang="scss">
:root {
  --nut-popover-white-background-color: rgba(255, 255, 255, 1);
  --nut-popover-dark-background-color: rgba(75, 76, 77, 1);
  --nut-popover-border-bottom-color: rgba(229, 229, 229, 1);
  --nut-popover-primary-text-color: rgba(51, 51, 51, 1);
  --nut-popover-disable-color: rgba(154, 155, 157, 1);
  --nut-popover-menu-item-padding: 8px 0;
  --nut-popover-menu-item-margin: 0 8px;
  --nut-popover-menu-name-line-height: normal;
}
</style>

// react-taro/src/components/popover/popover.tsx
import React, { useRef, useState } from 'react'
import { Button, Icon, Popover } from '@nutui/nutui-react-taro'
import './demo.scss'

interface List {
  name: string
  icon?: string
  disabled?: boolean
}

interface List {
  name: string
  icon?: string
  disabled?: boolean
}

const BadgeDemo = () => {
  const selfContentStyle = {
    width: '195px',
    display: 'flex',
    flexWrap: 'wrap',
  } as any
  const selfContentItem = {
    marginTop: '10px',
    marginBottom: '10px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
  } as any
  const selfContentDesc = {
    marginTop: '5px',
    width: '60px',
    fontSize: '10px',
    textAlign: 'center',
  } as any

  const itemList = [
    {
      name: '选项一',
    },
    {
      name: '选项二',
    },
    {
      name: '选项三',
    },
  ]
  const iconItemList = [
    {
      name: '选项一',
      icon: 'my2',
    },
    {
      name: '选项二',
      icon: 'cart2',
    },
    {
      name: '选项三',
      icon: 'location2',
    },
  ]
  const itemListDisabled = [
    {
      name: '选项一',
      disabled: true,
    },
    {
      name: '选项二',
      disabled: true,
    },
    {
      name: '选项三',
    },
  ]
  const selfContent = [
    {
      name: 'service',
      desc: '选项一',
    },
    {
      name: 'notice',
      desc: '选项二',
    },
    {
      name: 'location',
      desc: '选项三',
    },
    {
      name: 'category',
      desc: '选项四',
    },
    {
      name: 'scan2',
      desc: '选项五',
    },
    {
      name: 'message',
      desc: '选项六',
    },
  ]
  const [lightTheme, setLightTheme] = useState(false)
  const [darkTheme, setDarkTheme] = useState(false)
  const [showIcon, setShowIcon] = useState(false)
  const [disableAction, setDisableAction] = useState(false)
  const [customized, setCustomized] = useState(false)
  const customLocation = useRef([
    { bottom: false },
    { top: false },
    { left: false },
    { right: false },
    { 'top-start': false },
    { 'top-end': false },
    { 'bottom-start': false },
    { 'bottom-end': false },
    { 'left-start': false },
    { 'left-end': false },
    { 'right-start': false },
    { 'right-end': false },
  ])

  const [customLocationName, setCustomLocationName] = useState('top')
  const [customLocationShow, setCustomLocationShow] = useState(false)

  const chooseHandle = (item: List, index: number) => {
    console.log('选择')
  }

  return (
    <>
      <div className="demo">
        <h2>基础用法</h2>
        <Popover
          visible={lightTheme}
          onClick={() => {
            lightTheme ? setLightTheme(false) : setLightTheme(true)
          }}
          list={itemList}
          style={{ marginRight: '30px' }}
        >
          <Button type="primary" shape="square">
            明朗风格
          </Button>
        </Popover>
        <Popover
          visible={darkTheme}
          theme="dark"
          onClick={() => {
            darkTheme ? setDarkTheme(false) : setDarkTheme(true)
          }}
          list={itemList}
        >
          <Button type="primary" shape="square">
            暗黑风格
          </Button>
        </Popover>

        <h2>选项配置</h2>
        <Popover
          visible={showIcon}
          theme="dark"
          onClick={() => {
            showIcon ? setShowIcon(false) : setShowIcon(true)
          }}
          list={iconItemList}
          style={{ marginRight: '30px' }}
        >
          <Button type="primary" shape="square">
            展示图标
          </Button>
        </Popover>
        <Popover
          visible={disableAction}
          onClick={() => {
            disableAction ? setDisableAction(false) : setDisableAction(true)
          }}
          list={itemListDisabled}
          onChoose={chooseHandle}
        >
          <Button type="primary" shape="square">
            禁用选项
          </Button>
        </Popover>

        <h2>自定义内容</h2>
        <Popover
          visible={customized}
          onClick={() => {
            customized ? setCustomized(false) : setCustomized(true)
          }}
          location="bottom-start"
          className="customContent"
        >
          <Button type="primary" shape="square">
            自定义内容
          </Button>
          {customized ? (
            <div className="self-content" style={selfContentStyle}>
              {selfContent.map((item: any) => {
                return (
                  <div
                    className="self-content-item"
                    style={selfContentItem}
                    key={item.name}
                  >
                    <Icon name={item.name} size="15" />
                    <div className="self-content-desc" style={selfContentDesc}>
                      {item.desc}
                    </div>
                  </div>
                )
              })}
            </div>
          ) : (
            ''
          )}
        </Popover>

        <h2 className="demoClass">位置自定义</h2>

        <Popover
          visible={customLocationShow}
          location={customLocationName}
          onClick={() => {
            setCustomLocationShow(false)
          }}
          list={iconItemList}
          onChoose={chooseHandle}
          className="brickBox"
        >
          <div className="brick" />
        </Popover>

        <div className="customButtonBox">
          {customLocation.current.map((location, i) => {
            const k = Object.keys(location)[0] as any
            const v = Object.values(location)[0]
            return (
              <Button
                key={i}
                type="primary"
                shape="square"
                style={{ width: '160px', marginBottom: '8px' }}
                onClick={() => {
                  setCustomLocationName(k)
                  setCustomLocationShow(!customLocationShow)
                }}
              >
                {k} 弹出
              </Button>
            )
          })}
        </div>
      </div>
    </>
  )
}

export default BadgeDemo
