// react-taro/src/components/backtop/backtop.tsx
import React from 'react'
import { BackTop, Icon } from '@nutui/nutui-react-taro'
import { useTranslate } from '@/sites/assets/locale/taro'
import Header from '@/sites/components/header'
import Taro from '@tarojs/taro'

interface T {
  title: string
  clg: string
  backText: string
  content: string
}

const BackTopDemo = () => {
  const [translated] = useTranslate<T>({
    'zh-CN': {
      title: '基本用法',
      clg: '触发返回顶部',
      content: '我是测试数据',
      backText: '顶部',
    },
    'en-US': {
      title: 'Basic Usage',
      clg: 'backtop',
      content: 'test data',
      backText: 'Top',
    },
  })
  const demoStyle = {
    height: '1600px',
  }
  const cellStyle = {
    height: '46px',
    lineHeight: '46px',
    margin: '15px auto 20px',
    paddingLeft: '16px',
    backgroundColor: '#fff',
    color: '#666',
    borderRadius: '7px',
    boxShadow: '0 1px 7px #edeef1',
    fontSize: '13px',
  }

  const handleClick = () => {
    console.log(translated.clg)
  }

  return (
    <>
      <Header />
      <div
        className={`demo ${Taro.getEnv() === 'WEB' ? 'web' : ''}`}
        style={demoStyle}
        id="elId"
      >
        <h2>{translated.title}</h2>
        <div className="text-data" style={cellStyle}>
          {translated.content}1
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}2
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}3
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}4
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}5
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}6
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}7
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}8
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}9
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}10
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}11
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}12
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}13
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}14
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}15
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}16
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}17
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}18
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}19
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}20
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}21
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}22
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}23
        </div>
        <div className="text-data" style={cellStyle}>
          {translated.content}24
        </div>
        <BackTop
          className="custom-class"
          elId="elId"
          distance={100}
          bottom={110}
          onClick={handleClick}
        >
          <div
            className="backtop-demo"
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
            <Icon size="12px" className="nut-backtop-main" name="top" />
            <div style={{ fontSize: '12px' }}>{translated.backText}</div>
          </div>
        </BackTop>
        <BackTop elId="elId" distance={200} bottom={50} onClick={handleClick} />
      </div>
    </>
  )
}

export default BackTopDemo

// taro/src/pages/backtop/index.vue
<template>
  <div class="demo" id="elId">
    <div class="text-data">我是测试数据1</div>
    <div class="text-data">我是测试数据2</div>
    <div class="text-data">我是测试数据3</div>
    <div class="text-data">我是测试数据4</div>
    <div class="text-data">我是测试数据5</div>
    <div class="text-data">我是测试数据6</div>
    <div class="text-data">我是测试数据7</div>
    <div class="text-data">我是测试数据8</div>
    <div class="text-data">我是测试数据9</div>
    <div class="text-data">我是测试数据10</div>
    <div class="text-data">我是测试数据11</div>
    <div class="text-data">我是测试数据12</div>
    <div class="text-data">我是测试数据13</div>
    <div class="text-data">我是测试数据14</div>
    <div class="text-data">我是测试数据15</div>
    <div class="text-data">我是测试数据16</div>
    <div class="text-data">我是测试数据17</div>
    <div class="text-data">我是测试数据18</div>
    <div class="text-data">我是测试数据19</div>
    <div class="text-data">我是测试数据20</div>
    <div class="text-data">我是测试数据21</div>
    <div class="text-data">我是测试数据22</div>
    <div class="text-data">我是测试数据23</div>
    <div class="text-data">我是测试数据24</div>
    <div class="text-data">我是测试数据1</div>
    <div class="text-data">我是测试数据2</div>
    <div class="text-data">我是测试数据3</div>
    <div class="text-data">我是测试数据4</div>
    <div class="text-data">我是测试数据5</div>
    <div class="text-data">我是测试数据6</div>
    <div class="text-data">我是测试数据7</div>
    <div class="text-data">我是测试数据8</div>
    <div class="text-data">我是测试数据9</div>
    <div class="text-data">我是测试数据10</div>
    <div class="text-data">我是测试数据11</div>
    <div class="text-data">我是测试数据12</div>
    <div class="text-data">我是测试数据13</div>
    <div class="text-data">我是测试数据14</div>
    <div class="text-data">我是测试数据15</div>
    <div class="text-data">我是测试数据16</div>
    <div class="text-data">我是测试数据17</div>
    <div class="text-data">我是测试数据18</div>
    <div class="text-data">我是测试数据19</div>
    <div class="text-data">我是测试数据20</div>
    <div class="text-data">我是测试数据21</div>
    <div class="text-data">我是测试数据22</div>
    <div class="text-data">我是测试数据23</div>
    <div class="text-data">我是测试数据24</div>
    <div class="text-data">我是测试数据1</div>
    <div class="text-data">我是测试数据2</div>
    <div class="text-data">我是测试数据3</div>
    <div class="text-data">我是测试数据4</div>
    <div class="text-data">我是测试数据5</div>
    <div class="text-data">我是测试数据6</div>
    <div class="text-data">我是测试数据7</div>
    <div class="text-data">我是测试数据8</div>
    <div class="text-data">我是测试数据9</div>
    <div class="text-data">我是测试数据10</div>
    <div class="text-data">我是测试数据11</div>
    <div class="text-data">我是测试数据12</div>
    <div class="text-data">我是测试数据13</div>
    <div class="text-data">我是测试数据14</div>
    <div class="text-data">我是测试数据15</div>
    <div class="text-data">我是测试数据16</div>
    <div class="text-data">我是测试数据17</div>
    <div class="text-data">我是测试数据18</div>
    <div class="text-data">我是测试数据19</div>
    <div class="text-data">我是测试数据20</div>
    <div class="text-data">我是测试数据21</div>
    <div class="text-data">我是测试数据22</div>
    <div class="text-data">我是测试数据23</div>
    <div class="text-data">我是测试数据24</div>
    <nut-backtop @click="handleClick" el-id="elId" :distance="100" :bottom="90">
      <view>无</view>
    </nut-backtop>
    <nut-backtop
      @click="handleClick"
      el-id="elId"
      :distance="200"
    ></nut-backtop>
  </div>
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
  setup(props, { emit }) {
    const handleClick = () => {
      console.log('触发返回顶部');
    };

    return {
      handleClick
    };
  }
});
</script>

<style lang="scss" scoped>
.demo {
  .text-data {
    margin: 0 auto;
    margin-top: 15px;
    margin-bottom: 20px;
    padding-left: 16px;
    display: flex;
    align-items: center;
    width: 100%;
    height: 46px;
    background: rgba(255, 255, 255, 1);
    border-radius: 7px;
    box-shadow: 0px 1px 7px 0px rgba(237, 238, 241, 1);
    line-height: 19px;
    font-size: 13px;
    color: rgba(102, 102, 102, 1);
  }
}
</style>
