// v4-test/richard1015/vite/src/components/Countdown.vue
<script lang="ts" setup>
import { reactive, ref } from "vue";
const end = ref(Date.now() + 60 * 1000);
const serverTime = ref(Date.now() - 20 * 1000);
const asyncEnd = ref(0);
// 模拟异步时间
setTimeout(() => {
  asyncEnd.value = Date.now() + 30 * 1000;
}, 3000);
const state = reactive({
  paused: false,
  end: Date.now() + 60 * 1000,
});
const resetTime = ref({
  d: "1",
  h: "00",
  m: "00",
  s: "00",
});
const Countdown = ref<any>(null);
const start = () => {
  Countdown.value.start();
};
const pause = () => {
  Countdown.value.pause();
};
const reset = () => {
  Countdown.value.reset();
};

const toggle = () => {
  state.paused = !state.paused;
};
const onpaused = (v: any) => {
  console.log("paused: ", v);
};
const onrestart = (v: any) => {
  console.log("restart: ", v);
};
</script>
<template>
  <nut-cell>
    <nut-countdown :end-time="end"></nut-countdown>
  </nut-cell>
  <nut-cell>
    <nut-countdown :endTime="end" format="DD 天 HH 时 mm 分 ss 秒" />
  </nut-cell>
  <nut-cell>
    <nut-countdown :endTime="end" millisecond format="HH:mm:ss:SS" />
  </nut-cell>
  <nut-cell>
    <nut-countdown :startTime="serverTime" :endTime="end"></nut-countdown>
  </nut-cell>
  <nut-cell>
    <nut-countdown :end-time="asyncEnd"></nut-countdown>
  </nut-cell>
  <nut-cell>
    <nut-countdown
      :endTime="end"
      :paused="state.paused"
      @on-paused="onpaused"
      @on-restart="onrestart"
    />
    <div style="position: absolute; right: 10px; top: 9px">
      <nut-button type="primary" size="small" @click="toggle">{{
        state.paused ? "start" : "stop"
      }}</nut-button>
    </div>
  </nut-cell>
  <nut-cell>
    <nut-countdown v-model="resetTime" :endTime="end">
      <div class="countdown-part-box">
        <div class="part-item-symbol">{{ resetTime.d }}天</div>
        <div class="part-item h">{{ resetTime.h }}</div>
        <span class="part-item-symbol">:</span>
        <div class="part-item m">{{ resetTime.m }}</div>
        <span class="part-item-symbol">:</span>
        <div class="part-item s">{{ resetTime.s }}</div>
      </div>
    </nut-countdown>
  </nut-cell>
  <nut-cell>
    <nut-countdown
      time="20000"
      ref="Countdown"
      :autoStart="false"
      format="ss:SS"
    />
  </nut-cell>
  <nut-grid :column-num="3">
    <nut-grid-item
      ><nut-button type="primary" @click="start"
        >开始</nut-button
      ></nut-grid-item
    >
    <nut-grid-item
      ><nut-button type="primary" @click="pause"
        >暂停</nut-button
      ></nut-grid-item
    >
    <nut-grid-item
      ><nut-button type="primary" @click="reset"
        >重置</nut-button
      ></nut-grid-item
    >
  </nut-grid>
</template>
<style lang="scss">
.countdown-part-box {
  display: flex;
  align-items: center;

  .part-item {
    flex-shrink: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 20px;
    height: 25px;
    background: #e8220e;
    color: #fff;
    font-size: 14px;
    border-radius: 6px;
  }

  .part-item-symbol {
    margin: 0 5px;
  }
}
:root {
  --nut-countdown-display: flex;
  --nut-countdown-color: rgb(211, 12, 242);
  --nut-countdown-font-size: initial;
}
</style>

// react-taro-2.0/src/components/countdown/countdown.tsx
import React, { useEffect, useRef, useState } from 'react'
import Taro from '@tarojs/taro'
import {
  Button,
  Cell,
  CountDown,
  Grid,
  GridItem,
} from '@nutui/nutui-react-taro'
import Header from '@/sites/components/header'
import { useTranslate } from '@/sites/assets/locale/taro'

interface countdownRefState {
  start: () => void
  pause: () => void
  reset: () => void
}
interface T {
  basic: string
  format: string
  millisecond: string
  serverTime: string
  async: string
  controlTime: string
  customStyle: string
  handleControl: string
  start: string
  pause: string
  reset: string
  day: string
  hour: string
  minute: string
  second: string
}
const CountDownDemo = () => {
  const [translated] = useTranslate<T>({
    'zh-CN': {
      basic: '基本用法',
      format: '自定义格式',
      millisecond: '毫秒级渲染',
      serverTime: '以服务端的时间为准',
      async: '异步更新结束时间',
      controlTime: '控制开始和暂停的倒计时',
      customStyle: '自定义展示样式',
      handleControl: '手动控制',
      start: '开始',
      pause: '暂停',
      reset: '重置',
      day: '天',
      hour: '时',
      minute: '分',
      second: '秒',
    },
    'zh-TW': {
      basic: '基本用法',
      format: '自定义格式',
      millisecond: '毫秒级渲染',
      serverTime: '以服务端的时间为准',
      async: '异步更新结束时间',
      controlTime: '控制开始和暂停的倒计时',
      customStyle: '自定义展示样式',
      handleControl: '手动控制',
      start: '开始',
      pause: '暂停',
      reset: '重置',
      day: '天',
      hour: '时',
      minute: '分',
      second: '秒',
    },
    'en-US': {
      basic: 'Basic Usage',
      format: 'Custom Format',
      millisecond: 'Millisecond',
      serverTime: 'Server Time Prevails',
      async: 'End-Time of Asyn Update',
      controlTime: 'Manual Control',
      customStyle: 'Custom Style',
      handleControl: 'Handle Control',
      start: 'Start',
      pause: 'Pause',
      reset: 'Reset',
      day: 'Day',
      hour: ':',
      minute: ':',
      second: '',
    },
  })
  const stateRef = useRef({
    timer: -1,
    serverTime: Date.now() - 30 * 1000,
    endTime: Date.now() + 50 * 1000,
  })

  const countDownRef = useRef<countdownRefState>(null)

  const [paused, setPaused] = useState(false)
  const [asyncEnd, setAsyncEnd] = useState(0)
  const [resetTime, setResetTime] = useState({
    d: '1',
    h: '00',
    m: '00',
    s: '00',
  })

  const partItemStyle = {
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '20px',
    height: '25px',
    background: 'var(--nutui-brand-color)',
    color: '#fff',
    fontSize: '14px',
    borderRadius: '6px',
  }

  const partItemSymbolStyle = {
    margin: '0 5px',
  }

  useEffect(() => {
    stateRef.current.timer = window.setTimeout(() => {
      setAsyncEnd(Date.now() + 30 * 1000)
    }, 3000)
    return () => {
      clearTimeout(stateRef.current.timer)
    }
  }, [])

  const toggle = () => {
    console.log(paused)
    setPaused(!paused)
  }
  const onEnd = () => {
    console.log('countdown: ended.')
  }
  const onpaused = (v: number) => {
    console.log('paused: ', v)
  }
  const onrestart = (v: number) => {
    console.log('restart: ', v)
  }
  const onUpdate = (v: any) => {
    console.log('restTime: ', v)
    setResetTime(v)
  }
  const start = () => {
    console.log(countDownRef.current)
    countDownRef.current && countDownRef.current.start()
  }

  const pause = () => {
    countDownRef.current && countDownRef.current.pause()
  }

  const reset = () => {
    countDownRef.current && countDownRef.current.reset()
  }
  return (
    <>
      <Header />
      <div className={`demo ${Taro.getEnv() === 'WEB' ? 'web' : ''}`}>
        <h2>{translated.basic}</h2>
        <Cell>
          <CountDown
            endTime={stateRef.current.endTime}
            onUpdate={onUpdate}
            onEnd={onEnd}
          />
        </Cell>
        <h2>{translated.format}</h2>
        <Cell>
          <CountDown
            endTime={stateRef.current.endTime}
            format={`DD ${translated.day} HH ${translated.hour} mm ${translated.minute} ss ${translated.second}`}
          />
        </Cell>

        <h2>{translated.millisecond}</h2>
        <Cell>
          <CountDown
            endTime={stateRef.current.endTime}
            millisecond
            format="HH:mm:ss:SS"
          />
        </Cell>

        <h2>{translated.serverTime}</h2>
        <Cell>
          <CountDown
            startTime={stateRef.current.serverTime}
            endTime={stateRef.current.endTime}
          />
        </Cell>

        <h2>{translated.async}</h2>
        <Cell>
          <CountDown endTime={asyncEnd} />
        </Cell>

        <h2>{translated.controlTime}</h2>
        <Cell>
          <CountDown
            endTime={stateRef.current.endTime}
            paused={paused}
            onPaused={onpaused}
            onRestart={onrestart}
          />
          <div style={{ position: 'absolute', right: '10px', top: '9px' }}>
            <div onClick={() => toggle()}>
              <Button type="primary" size="small">
                {paused ? 'start' : 'stop'}
              </Button>
            </div>
          </div>
        </Cell>

        <h2>{translated.customStyle}</h2>
        <Cell>
          <span>
            <CountDown endTime={stateRef.current.endTime} onUpdate={onUpdate}>
              <div
                className="countdown-part-box"
                style={{ display: 'flex', alignItems: 'center' }}
              >
                <div className="part-item-symbol" style={partItemSymbolStyle}>
                  {resetTime.d}天
                </div>
                <div className="part-item h" style={partItemStyle}>
                  {resetTime.h}
                </div>
                <span className="part-item-symbol" style={partItemSymbolStyle}>
                  :
                </span>
                <div className="part-item m" style={partItemStyle}>
                  {resetTime.m}
                </div>
                <span className="part-item-symbol" style={partItemSymbolStyle}>
                  :
                </span>
                <div className="part-item s" style={partItemStyle}>
                  {resetTime.s}
                </div>
              </div>
            </CountDown>
          </span>
        </Cell>

        <h2>{translated.handleControl}</h2>
        <Cell>
          <CountDown
            format="ss:SS"
            autoStart={false}
            time={20000}
            ref={countDownRef}
          />
        </Cell>
        <Grid columns="3" style={{ marginBottom: '5px' }}>
          <GridItem>
            <Button type="primary" onClick={start}>
              {translated.start}
            </Button>
          </GridItem>
          <GridItem>
            <Button type="primary" onClick={pause}>
              {translated.pause}
            </Button>
          </GridItem>
          <GridItem>
            <Button type="primary" onClick={reset}>
              {translated.reset}
            </Button>
          </GridItem>
        </Grid>
      </div>
    </>
  )
}

export default CountDownDemo
