// taro/src/pages/infiniteloading/index.vue
<template>
  <div class="demo">
    <h2>基础用法</h2>
    <nut-cell>
      <ul class="infiniteUl" id="scroll">
        <nut-infiniteloading
          container-id="scroll"
          :use-window="false"
          :has-more="hasMore"
          @load-more="loadMore"
        >
          <li
            class="infiniteLi"
            v-for="(item, index) in defultList"
            :key="index"
            >{{ item }}</li
          >
        </nut-infiniteloading>
      </ul>
    </nut-cell>

    <h2>下拉刷新</h2>
    <nut-cell>
      <ul class="infiniteUl" id="refreshScroll">
        <nut-infiniteloading
          pull-icon="JD"
          container-id="refreshScroll"
          :use-window="false"
          :is-open-refresh="true"
          :has-more="refreshHasMore"
          @load-more="refreshLoadMore"
          @refresh="refresh"
        >
          <li
            class="infiniteLi"
            v-for="(item, index) in refreshList"
            :key="index"
            >{{ item }}</li
          >
        </nut-infiniteloading>
      </ul>
    </nut-cell>

    <h2>自定义加载文案</h2>
    <nut-cell>
      <ul class="infiniteUl" id="customScroll">
        <nut-infiniteloading
          load-txt="loading"
          load-more-txt="没有啦～"
          container-id="customScroll"
          :use-window="false"
          :has-more="customHasMore"
          @load-more="customLoadMore"
        >
          <li
            class="infiniteLi"
            v-for="(item, index) in customList"
            :key="index"
            >{{ item }}</li
          >
        </nut-infiniteloading>
      </ul>
    </nut-cell>
  </div>
</template>

<script lang="ts">
import { onMounted, ref, reactive, toRefs, defineComponent } from 'vue';
export default defineComponent({
  props: {},
  setup() {
    const hasMore = ref(true);
    const customHasMore = ref(true);
    const refreshHasMore = ref(true);

    const data = reactive({
      defultList: [''],
      customList: [''],
      refreshList: ['']
    });

    const loadMore = done => {
      setTimeout(() => {
        const curLen = data.defultList.length;

        for (let i = curLen; i < curLen + 10; i++) {
          data.defultList.push(
            `${i} -- 塑像本来就在石头里，我只是把不要的部分去掉`
          );
        }

        if (data.defultList.length > 30) hasMore.value = false;

        done();
      }, 500);
    };

    const customLoadMore = done => {
      setTimeout(() => {
        const curLen = data.customList.length;
        for (let i = curLen; i < curLen + 10; i++) {
          data.customList.push(
            `${i} -- 塑像本来就在石头里，我只是把不要的部分去掉`
          );
        }
        if (data.customList.length > 30) customHasMore.value = false;
        done();
      }, 500);
    };

    const refreshLoadMore = done => {
      setTimeout(() => {
        const curLen = data.refreshList.length;
        for (let i = curLen; i < curLen + 10; i++) {
          data.refreshList.push(
            `${i} -- 塑像本来就在石头里，我只是把不要的部分去掉`
          );
        }
        if (data.refreshList.length > 30) refreshHasMore.value = false;
        done();
      }, 500);
    };

    const refresh = done => {
      setTimeout(() => {
        console.log('success')
        done();
      }, 1000);
    };

    const init = () => {
      for (let i = 0; i < 10; i++) {
        data.defultList.push(
          `${i} -- 塑像本来就在石头里，我只是把不要的部分去掉`
        );
        data.customList.push(
          `${i} -- 塑像本来就在石头里，我只是把不要的部分去掉`
        );
        data.refreshList.push(
          `${i} -- 塑像本来就在石头里，我只是把不要的部分去掉`
        );
      }
    };
    onMounted(() => {
      init();
    });

    return {
      loadMore,
      hasMore,
      customHasMore,
      customLoadMore,
      refreshHasMore,
      refreshLoadMore,
      refresh,
      ...toRefs(data)
    };
  }
});
</script>

<style lang="scss" scoped>
.infiniteUl {
  height: 300px;
  width: 100%;
  overflow-y: auto;
  overflow-x: hidden;
}
.infiniteLi {
  margin-top: 10px;
  font-size: 14px;
  color: rgba(100, 100, 100, 1);
}

.loading {
  display: block;
  width: 100%;
  text-align: center;
}
</style>

// react-taro/src/components/infiniteloading/infiniteloading.tsx
import React, { useState, useEffect } from 'react'
import { useTranslate } from '@/sites/assets/locale/taro'
import { Infiniteloading, Cell, Toast } from '@nutui/nutui-react-taro'
import './demo.scss'

interface T {
  '83913e71': string
  '84aa6bce': string
  eb4236fe: string
  '9ed40460': string
  '1254a90a': string
}
const InfiniteloadingDemo = () => {
  const [translated] = useTranslate<T>({
    'zh-CN': {
      '83913e71': '刷新成功',
      '84aa6bce': '基础用法',
      eb4236fe: '下拉刷新',
      '9ed40460': '自定义加载文案',
      '1254a90a': '没有啦~',
    },
    'zh-TW': {
      '83913e71': '刷新成功',
      '84aa6bce': '基礎用法',
      eb4236fe: '下拉刷新',
      '9ed40460': '自定義加載文案',
      '1254a90a': '沒有啦~',
    },
    'en-US': {
      '83913e71': 'Refresh successfully',
      '84aa6bce': 'Basic usage',
      eb4236fe: 'Pull down to refresh',
      '9ed40460': 'custom loading text',
      '1254a90a': 'nope~',
    },
  })

  const [defultList, setDefultList] = useState<string[]>([])
  const [customList, setCustomList] = useState<string[]>([])
  const [refreshList, setRefreshList] = useState<string[]>([])
  const [hasMore, setHasMore] = useState(true)
  const [customHasMore, setCustomHasMore] = useState(true)
  const [refreshHasMore, setRefreshHasMore] = useState(true)

  useEffect(() => {
    init()
  }, [])

  const loadMore = (done: () => void) => {
    setTimeout(() => {
      const curLen = defultList.length
      for (let i = curLen; i < curLen + 10; i++) {
        defultList.push(`${i}`)
      }
      if (defultList.length >= 30) {
        setHasMore(false)
      } else {
        setDefultList([...defultList])
      }
      done()
    }, 500)
  }

  const refreshLoadMore = (done: () => void) => {
    setTimeout(() => {
      const curLen = refreshList.length
      for (let i = curLen; i < curLen + 10; i++) {
        refreshList.push(`${i}`)
      }
      if (refreshList.length >= 30) {
        setRefreshHasMore(false)
      } else {
        setRefreshList([...refreshList])
      }
      done()
    }, 500)
  }

  const customLoadMore = (done: () => void) => {
    setTimeout(() => {
      const curLen = customList.length
      for (let i = curLen; i < curLen + 10; i++) {
        customList.push(`${i}`)
      }
      if (customList.length >= 30) {
        setCustomHasMore(false)
      } else {
        setCustomList([...customList])
      }
      done()
    }, 500)
  }

  const refresh = (done: () => void) => {
    setTimeout(() => {
      Toast.text(translated['83913e71'])
      done()
    }, 1000)
  }

  const init = () => {
    for (let i = 0; i < 10; i++) {
      defultList.push(`${i}`)
      customList.push(`${i}`)
      refreshList.push(`${i}`)
    }
    setDefultList([...defultList])
    setCustomList([...customList])
    setRefreshList([...refreshList])
  }

  return (
    <>
      <div className="demo">
        <h2>{translated['84aa6bce']}</h2>
        <Cell>
          <ul className="infiniteUl" id="scroll">
            <Infiniteloading
              containerId="scroll"
              useWindow={false}
              hasMore={hasMore}
              loadMore={loadMore}
            >
              {defultList.map((item, index) => {
                return (
                  <li className="infiniteLi" key={index}>
                    {item}
                  </li>
                )
              })}
            </Infiniteloading>
          </ul>
        </Cell>

        <h2>{translated['9ed40460']}</h2>
        <Cell>
          <ul className="infiniteUl" id="customScroll">
            <Infiniteloading
              containerId="customScroll"
              useWindow={false}
              loadTxt="loading"
              loadMoreTxt={translated['1254a90a']}
              hasMore={customHasMore}
              loadMore={customLoadMore}
            >
              {customList.map((item, index) => {
                return (
                  <li className="infiniteLi" key={index}>
                    {item}
                  </li>
                )
              })}
            </Infiniteloading>
          </ul>
        </Cell>
      </div>
    </>
  )
}

export default InfiniteloadingDemo
