// react-taro-2.0/src/components/table/table.tsx
import React, { useState } from 'react'
import Taro from '@tarojs/taro'
import { Dongdong, TriangleDown } from '@nutui/icons-react-taro'
import { useTranslate } from '@/sites/assets/locale/taro'
import { Button, Toast, Table } from '@nutui/nutui-react-taro'
import Header from '@/sites/components/header'

interface T {
  basic: string
  borderedAndAlign: string
  summaryTitle: string
  summary: string
  striped: string
  noDataTitle: string
  customNoData: string
  customCell: string
  asynchronousRendering: string
  sorting: string
  sorterIcon: string
  hideHeader: string
}

const TableDemo = () => {
  const [translated] = useTranslate<T>({
    'zh-CN': {
      basic: '基础用法',
      borderedAndAlign: '是否显示边框，文字对齐',
      summaryTitle: '显示总结栏',
      summary: '这是总结栏',
      striped: '条纹、明暗交替',
      hideHeader: '隐藏表头',
      noDataTitle: '无数据默认展示，支持自定义',
      customNoData: '这里是自定义展示',
      customCell: '自定义单元格',
      asynchronousRendering: '支持异步渲染(5s之后看效果)',
      sorting: '支持排序',
      sorterIcon: '支持排序更换图标',
    },
    'en-US': {
      basic: 'Basic usage',
      borderedAndAlign: 'Whether to display border and align text',
      summaryTitle: 'Show summary bar',
      summary: 'This is the summary column',
      striped: 'Stripes, alternating light and shade',
      hideHeader: 'Hide table header',
      noDataTitle:
          'No data is displayed by default, and customization is supported',
      customNoData: 'Here is the custom display',
      customCell: 'Custom cell',
      asynchronousRendering:
          'Support asynchronous rendering(See the effect after 5S)',
      sorting: 'Support sorting',
      sorterIcon: 'Supports sorting and changing ICONS',
    },
  })

  const [columns1, ] = useState<Array<any>>([
    {
      title: '姓名',
      key: 'name',
    },
    {
      title: '性别',
      key: 'sex',
      render: (record: any) => {
        return (
            <span style={{ color: record.sex === '女' ? 'blue' : 'green' }}>
            {record.sex}
          </span>
        )
      },
    },
    {
      title: '学历',
      key: 'record',
    },
  ])
  const [columns2, ] = useState<Array<any>>([
    {
      title: '姓名',
      key: 'name',
      align: 'center',
    },
    {
      title: '性别',
      key: 'sex',
    },
    {
      title: '学历',
      key: 'record',
    },
  ])

  const [columns4, ] = useState<Array<any>>([
    {
      title: '姓名',
      key: 'name',
      align: 'center',
    },
    {
      title: '性别',
      key: 'sex',
    },
    {
      title: '学历',
      key: 'record',
    },
    {
      title: '操作',
      key: 'render',
    },
  ])

  const [columns5, ] = useState<Array<any>>([
    {
      title: '姓名',
      key: 'name',
      align: 'center',
      sorter: true,
    },
    {
      title: '性别',
      key: 'sex',
    },
    {
      title: '学历',
      key: 'record',
    },
    {
      title: '年龄',
      key: 'age',
      sorter: (row1: any, row2: any) => {
        return row1.age - row2.age
      },
    },
  ])

  const [data1, setData1] = useState([
    {
      name: 'Tom',
      sex: '男',
      record: '小学',
    },
    {
      name: 'Lucy',
      sex: '女',
      record: '本科',
    },
    {
      name: 'Jack',
      sex: '男',
      record: '高中',
    },
  ])

  const [data2, ] = useState([])
  const [data3, setData3] = useState<any>([])
  const [data4, ] = useState([
    {
      name: 'Tom',
      sex: '男',
      record: '小学',
      render: () => {
        return (
            <Button
                size="small"
                type="primary"
            >
              <div>Hello</div>
            </Button>
        )
      },
    },
    {
      name: 'Lucy',
      sex: '女',
      record: '本科',
      render: () => {
        return <Dongdong height="14px" width="14px" />
      },
    },
    {
      name: 'Jack',
      sex: '男',
      record: '高中',
      render: () => {
        return (
            <Button
                type="success"
                size="small"
                onClick={() => window.open('https://www.jd.com')}
            >
              <div>跳转到京东</div>
            </Button>
        )
      },
    },
  ])

  const [data5, setData5] = useState([
    {
      name: 'Tom',
      sex: '男',
      record: '小学',
      age: 10,
    },
    {
      name: 'Lucy',
      sex: '女',
      record: '本科',
      age: 30,
    },
    {
      name: 'Jack',
      sex: '男',
      record: '高中',
      age: 4,
    },
  ])

  setTimeout(() => {
    setData3(data1)
  }, 5000)

  const handleSorter = (item: any, data: Array<any>) => {
    setData5([...data])
  }

  return (
      <>
        <div className="demo">
          <h2>{translated.basic}</h2>
          <Table columns={columns1} data={data1} style={{ background: '#fff' }} />
          <h2>{translated.borderedAndAlign}</h2>
          <Table
              columns={columns2}
              data={data1}
              bordered={false}
              style={{ background: '#fff' }}
          />
          <h2>{translated.summaryTitle}</h2>
          <Table
              columns={columns1}
              data={data1}
              summary={translated.summary}
              style={{ background: '#fff' }}
          />
          <h2>{translated.striped}</h2>
          <Table
              columns={columns1}
              data={data1}
              style={{ background: '#fff' }}
              striped
          />
          <h2>{translated.hideHeader}</h2>
          <Table
              columns={columns1}
              data={data1}
              style={{ background: '#fff' }}
              showHeader={false}
          />
          <h2>{translated.noDataTitle}</h2>
          <Table columns={columns1} data={data2} style={{ background: '#fff' }} />
          <Table
              columns={columns1}
              data={data2}
              style={{ background: '#fff' }}
              noData={translated.customNoData}
          />
          <h2>{translated.customCell}</h2>
          <Table columns={columns4} data={data4} style={{ background: '#fff' }} />
          <h2>{translated.asynchronousRendering}</h2>
          <Table columns={columns1} data={data3} style={{ background: '#fff' }} />
          <h2>{translated.sorting}</h2>
          <Table
              columns={columns5}
              data={data5}
              onSort={handleSorter}
              style={{ background: '#fff' }}
          />
          <h2>{translated.sorterIcon}</h2>
          <Table
              columns={columns5}
              data={data5}
              onSort={handleSorter}
              style={{ background: '#fff' }}
              sorterIcon={<TriangleDown width="12px" height="12px" />}
          />
        </div>
      </>
  )
}

export default TableDemo

// taro/src/business/pages/table/index.vue
<template>
  <div class="demo">
    <h2>基础用法</h2>
    <nut-table :columns="columns1" :data="data1"></nut-table>
    <h2>是否显示边框，文字对齐</h2>
    <nut-table :columns="columns2" :data="data1" :bordered="bordered1"></nut-table>
    <h2>显示总结栏</h2>
    <nut-table :columns="columns3" :data="data2" :summary="summary"></nut-table>
    <h2>条纹、明暗交替</h2>
    <nut-table :columns="columns3" :data="data2" :striped="striped"></nut-table>
    <h2>无数据默认展示，支持自定义</h2>
    <nut-table :columns="columns3" :data="data3"> </nut-table>
    <br />
    <nut-table :columns="columns3" :data="data3">
      <template #nodata>
        <div class="no-data"> 这里是自定义展示 </div>
      </template>
    </nut-table>
    <h2>自定义单元格</h2>
    <nut-table :columns="columns4" :data="data4"> </nut-table>
    <h2>支持异步渲染(5s之后看效果)</h2>
    <nut-table :columns="columns3" :data="data5"> </nut-table>
    <h2>支持排序</h2>
    <nut-table :columns="columns6" :data="data6" @sorter="handleSorter"> </nut-table>
  </div>
</template>

<script lang="ts">
import { reactive, toRefs, onMounted, onUnmounted, h, defineComponent } from 'vue';
import {Button,Icon,} from '@nutui/nutui-taro'
export default defineComponent({
  components: {
    Button,
    Icon
  },
  props: {},
  setup(props, { emit, slot }) {
    const state = reactive({
      bordered1: false,
      striped: true,
      columns1: [
        {
          title: '姓名',
          key: 'name'
        },
        {
          title: '性别',
          key: 'sex'
        },
        {
          title: '学历',
          key: 'record'
        }
      ],
      columns2: [
        {
          title: '姓名',
          key: 'name',
          align: 'center'
        },
        {
          title: '性别',
          key: 'sex'
        },
        {
          title: '学历',
          key: 'record'
        }
      ],
      columns3: [
        {
          title: '姓名',
          key: 'name'
        },
        {
          title: '性别',
          key: 'sex'
        },
        {
          title: '学历',
          key: 'record'
        },
        {
          title: '年龄',
          key: 'age'
        },
        {
          title: '地址',
          key: 'address'
        }
      ],
      columns4: [
        {
          title: '姓名',
          key: 'name',
          align: 'center'
        },
        {
          title: '性别',
          key: 'sex'
        },
        {
          title: '学历',
          key: 'record'
        },
        {
          title: '操作',
          key: 'render'
        }
      ],
      columns6: [
        {
          title: '姓名',
          key: 'name',
          align: 'center',
          sorter: true
        },
        {
          title: '性别',
          key: 'sex'
        },
        {
          title: '学历',
          key: 'record'
        },
        {
          title: '年龄',
          key: 'age',
          sorter: (row1: any, row2: any) => {
            return row1.age - row2.age;
          }
        }
      ],
      data1: [
        {
          name: 'Tom',
          sex: '男',
          record: '小学'
        },
        {
          name: 'Lucy',
          sex: '女',
          record: '本科'
        },
        {
          name: 'Jack',
          sex: '男',
          record: '高中'
        }
      ],
      data2: [
        {
          name: 'Tom',
          sex: '男',
          record: '小学',
          age: 13,
          address: '北京'
        },
        {
          name: 'Lucy',
          sex: '女',
          record: '本科',
          age: 34,
          address: '上海'
        },
        {
          name: 'Jack',
          sex: '男',
          record: '高中',
          age: 4,
          address: '杭州'
        }
      ],
      data3: [],
      data4: [
        {
          name: 'Tom',
          sex: '男',
          record: '小学',
          render: () => {
            return h(Button, { size: 'small', type: 'primary' }, 'Hello');
          }
        },
        {
          name: 'Lucy',
          sex: '女',
          record: '本科',
          render: () => {
            return h(Icon, { name: 'dongdong', size: '14px' });
          }
        },
        {
          name: 'Jack',
          sex: '男',
          record: '高中',
          render: () => {
            return h(Button, { type: 'success', size: 'small' }, '编辑按钮');
          }
        }
      ],
      data5: [],
      data6: [
        {
          name: 'Tom',
          sex: '男',
          record: '小学',
          age: 10
        },
        {
          name: 'Lucy',
          sex: '女',
          record: '本科',
          age: 30
        },
        {
          name: 'Jack',
          sex: '男',
          record: '高中',
          age: 4
        }
      ],
      timer: null as number | null,
      summary: () => {
        return {
          value: '这是总结栏',
          colspan: 5
        };
      }
    });

    const handleSorter = (item: any) => {
      console.log(JSON.stringify(item));
    };

    onMounted(() => {
      state.timer = setTimeout(() => {
        state.data5 = state.data2.slice() as any;
      }, 5000);
    });

    onUnmounted(() => {
      state.timer = null;
    });

    return {
      ...toRefs(state),
      handleSorter
    };
  }
});
</script>

<style lang="scss">
.demo {
  padding-bottom: 20px !important;
}
.nut-table {
  background-color: #fff;
}
</style>
