// react-taro/src/components/rate/rate.tsx
import React from 'react'
import Taro from '@tarojs/taro'
import { Rate } from '@nutui/nutui-react-taro'

const RateDemo = () => {
  const onChange = (val: any) => {
    Taro.showToast({ title: String(val) })
  }
  return (
    <>
      <div className="demo">
        <h2>基础用法</h2>
        <Rate modelValue={3} />
        <h2>半星</h2>
        <Rate
          allowHalf
          modelValue="3.5"
          change={(num) => console.log('allowHalf count', num)}
        />

        <h2>自定义 icon </h2>
        <Rate
          checkedIcon="heart-fill1"
          uncheckedIcon="heart"
          modelValue="3"
          change={(num) => console.log('coustom icon count', num)}
        />

        <h2>自定义数量</h2>
        <Rate count="6" modelValue="3" />

        <h2>最少选中数量（支持半星）</h2>
        <Rate
          modelValue="2"
          minimizeValue={3}
          change={(num) => console.log(num)}
        />

        <h2>自定义颜色</h2>
        <Rate activeColor="#FFC800" modelValue="3" />

        <h2>禁用状态</h2>
        <Rate disabled modelValue="3" />

        <h2>只读状态</h2>
        <Rate modelValue="3" readonly />

        <h2>绑定事件</h2>
        <Rate modelValue="3" change={onChange} />

        <h2>自定义尺寸 35px</h2>
        <Rate modelValue="3" iconSize="35" />
      </div>
    </>
  )
}

export default RateDemo

// taro/src/pages/rate/index.vue
<template>
  <div class="demo">
    <h2>基本用法</h2>
    <nut-rate v-model="state.val" />

    <h2>半星</h2>
    <nut-rate allow-half v-model="state.val1"></nut-rate>

    <h2>自定义 icon </h2>
    <nut-rate
      checked-icon="heart-fill1"
      unchecked-icon="heart"
      v-model="state.val2"
    ></nut-rate>

    <h2>自定义数量</h2>
    <nut-rate :count="6" v-model="state.val3"></nut-rate>

    <h2>自定义颜色</h2>
    <nut-rate active-color="#FFC800" v-model="state.val4"></nut-rate>

    <h2>禁用状态</h2>
    <nut-rate disabled v-model="state.val5"></nut-rate>

    <h2>只读状态</h2>
    <nut-rate v-model="state.val6" readonly></nut-rate>

    <h2>绑定事件</h2>
    <nut-rate v-model="state.val7" @change="onChange"></nut-rate>
    <h2>自定义尺寸 35px</h2>
    <nut-rate v-model="state.val8" icon-size="35"></nut-rate>
  </div>
</template>

<script>
import { reactive, getCurrentInstance, defineComponent } from 'vue';
export default defineComponent({
  setup() {
    let { proxy } = getCurrentInstance();

    const state = reactive({
      val: 3,
      val1: 3.5,
      val2: 3,
      val3: 3,
      val4: 3,
      val5: 3,
      val6: 3,
      val7: 3,
      val8: 3
    });
    const onChange = val => {
      console.log(val)
    };
    return {
      state,
      onChange
    };
  }
});
</script>

<style lang="scss" scoped></style>
